api_recipe_get_all:
    path: /api/recipes
    defaults:
        _controller: AppBundle:Default:showAllRecipes
        _format: json
    methods:  [GET]
api_recipe_get:
    path: /api/recipes/{id}
    defaults:
        _controller: AppBundle:Default:showRecipe
        _format: json
    methods:  [GET]